#!/snap/bin/node

let urllib = require("urllib");
let url = process.argv[2];
console.log("the url is: " + url);

let fs = require("fs");
if(url) {
    const jsdom = require("jsdom");
    const { JSDOM } = jsdom;

    urllib.request(url, {followRedirect : true}, function (error, data, response) {
        let body = data.toString();   
    
        //simulate a document object model
        let { document } = (new JSDOM(body)).window;
        let paragraphs = document.querySelectorAll("p");
        console.log(paragraphs.length);
        let references = document.querySelectorAll(".reference");
        references.forEach(reference => reference.remove());
        paragraphs.forEach(function (paragraph) {
            console.log(paragraph.textContent);
            fs.appendFileSync("wiki.txt", paragraph.textContent)

        });
})
} else {
    console.log("enter a valid url");
    //process.exit(1);
}


